#!/bin/sh

find . -name "*.h" -o -name "*.c" -o -name "*.cc" -o -name "*.cpp"  > cscope.files
cscope -bkq -i cscope.files
ctags -R
ctags -n -f cppcomplete.tags --fields=+ai --C++-types=+p * -L cscope.files
cp ~/utils/workspace.vim ./workspace.vim
